<?php
/**
 * Copyright (C) 2016 Adam Schubert <adam.schubert@sg1-game.net>.
 */

namespace Salamek\PplMyApi\Enum;

/**
 * Description of ReturnCode
 *
 * @author sadam
 */
class ReturnCode {
    const LOADED_SUCCESSFULLY = 0;
    const LOADED_UNSUCCESSFULLY = 1;
    const INVALID_OR_MISSING_PACKAGE_NUMBER = 1000;
    const UNKNOWN_PRODUCT_TYPE = 1001;
    const BAD_SENDER_ADDRESS = 1002;
    const BAD_RECIPIENT_ADDRESS = 1003;
    const INVALID_COD_VARIABLE_SYMBOL = 1004;
    const INVALID_SPECIAL_SYMBOL = 1005;
    const COD_PRICE_AND_COD_CURRENCY_NOT_FILLED_BOTH = 1006;
    const COD_NEGATIVE_PRICE = 1007;
    const INVALID_BANK_INFORMATIONS_FILLED_BANK_ACCOUNT_CODE_AND_ALSO_IBAN_SWIFT = 1008;
    const BANK_ACCOUNT_AND_BANK_CODE_MUST_BE_FILLED_BOTH = 1009;
    const IBAN_AND_SWIFT_MUST_BE_FILLED_BOTH = 1010;
    const UNKNOWN_BANK_CODE = 1011;
    const UNKNOWN_SWIFT_CODE = 1012;
    const FILLED_COD_INFORMATIONS_FOR_NONCOD_PRODUCT = 1013;
    
    const UNKNOWN_PARCELSHOP_CODE = 1023;
    const INVALID_PACKAGE_WEIGHT = 1024;
    const INSURANCE_PRICE_AND_CURRENCY_MUST_BE_FILLED_BOTH = 1025;
    const INSURANCE_NEGATIVE_PRICE = 1026;
    const UNKNOWN_COD_CURRENCY = 1027;
    const UNKNOWN_INSURANCE_CURRENCY = 1028;
    const UNKNOWN_PACKAGE_SERVICE = 1029;
    const UNKNOWN_EXTERNAL_NUMBER = 1030;
    const INVALID_COUNTRY_IN_SENDER_ADDRESS = 1031;
    const INVALID_COUNTRY_IN_RECIPIENT_ADDRESS = 1032;
    const INVALID_INFORMATIONS_ABOUT_WEIGHTED_PACKAGES = 1033;
    const UNKNOWN_ROUTES = 1034;
    const INVALID_PACKAGE_WEIGHT_100X = 1035;  //!FIXME duplicty with 1024
    const SATURDAY_DELIVERY_FILLED_AND_SATURDAY_ROUTE_NOT_OR_VICE_VERSA = 1036;
    const MISSING_INPUT_DESTINATION = 1037;
    const MISSING_OUTPUT_DESTINATION = 1038;
    const FILLED_ROUTE_TYPE_IN_AND_NOT_ROUTE_TYPE_OUT_OR_VICE_VERSA_TWO_TIMES_FILLED_ROUTE_TYPE_OUT_OR_ROUTE_TYPE_IN = 1039;
    const UNKNOWN_PACKAGE_FLAG = 1040;
    
    
    // CreatePackages
    const SPECTAKEDATE_MUST_BE_EQUAL_OR_GREATER_THAN_THE_CURRENT_DATE = 1033;
    const SERVICE_IS_NOT_RELEVANT_FOR_PRODUCT_TYPE = 1035;
    
    const SD_FLAG_CANT_BE_SPECIFIED_FOR_THIS_PRODUCT_TYPE = 1043;
    const RECIPIENT_COUTRY_ZIPCODE_WRONG_CHECK_THE_FORMAT = 1046;
    const BAD_SENDER_ZIPCODE_FORMAT = 1047;
    const PARAMETER_SPECTAKEDATE_MUST_BE_SPECIFIED = 1048;
    const COD_PRICE_IS_GREATER_THAN_THE_MAXIMUM_ALLOWABLE_LIMIT_FOR_THE_COUNTRY = 1049;
    const MAXIMUM_NUMBER_OF_PACKAGES_EXCEEDED = 1050;
    const VALUE_OF_KEY_WITH_NAME_MAXINSURANCE_MAXCODPRICE_MAXPACKAGESINCOUNT_IS_NOT_DECIMAL = 1051;
    const THE_PACKNUMBER_IS_REQUIRED_FIELD = 1052;
    const DUPLICIT_PACKNUMBER = 1053;
    const INSURANCE_PRICE_MUST_BE_LOWER_OR_EQUAL_TO = 1054;
    const MAXIMUM_NUMBER_OF_PACKAGES_EXCEEDED_100X = 1055; //!FIXME duplicit with 1050
    const THE_PACKNUMBER_IS_REQUIRED_FIELD_100X = 1057;  //!FIXME duplicit with 1052
    const DUPLICIT_PACKNUMBER_100X = 1058; //!FIXME duplicit with 1053
    const PACKAGE_PACKNUMBER_IS_NOT_AUTHORIZED_TO_CREATE_BACK_DOCUMENTS = 1059;
    const PACKAGE_PACKNUMBER_DOCUMENTSBACK_PACKNUMBER_IS_MISSING = 1060;
    const PACKAGE_PACKNUMBER_SERVICE_WITH_CODE_DB_IS_MISSING = 1061;
    const INVALID_RECIPIENT_ADDRESS_FOR_BACK_DOCUMENTS = 1062;
    const RECIPIENT_ZIP_CODE_DOESNT_SUPPORT_MORNING_DELIVERY = 1063;
    const PACKAGEINSETNR_IS_HIGHER_THEN_PACKAGEINSET = 1065;
    const MISSING_RETURN_CZ_SERVICE_RECIPIENT_ADDRESS = 1067;
    const MISSING_RETURN_CZ_BACKPACKNUMBER = 1068;

    
    
    // CreatePickUpOrders
    const BAD_SENDER_ADDRESS_200X = 2001;  //!FIXME duplicty with 1002
    const BAD_COUNT_OF_PACKAGES = 2002;
    const INVALID_COUNTRY_IN_SENDER_ADDRESS_200X = 2005; //!FIXME duplicty with 1031
    const SENDDATE_MUST_BE_EQUAL_OR_GREATER_THAN_THE_CURRENT_DATE = 2006;
    const PARAMETER_SENDDATE_MUST_BE_FILLED = 2008;

    
    // CreateOrders
    const BAD_RECIPIENT_ADDRESS_300X = 3001;  //!FIXME duplicty with  1003
    const BAD_SENDER_ADDRESS_300X = 3002; //!FIXME duplicty with  1002
    const BAD_COUNT_OF_PACKAGES_300X = 3003; //!FIXME duplicty with  2002
    const UNKNOWN_PRODUCT_TYPE_FOR_PACKAGE = 3004;
    const INVALID_COUNTRY_IN_SENDER_ADDRESS_300X = 3005; //!FIXME duplicty with  1031
    const INVALID_COUNTRY_IN_RECIPIENT_ADDRESS_300X = 3006; //!FIXME duplicty with  1032
    const SENDDATE_MUST_BE_EQUAL_OR_GREATER_THAN_THE_CURRENT_DATE_300X = 3007; //!FIXME duplicity with 2006
    const PARAMETER_SENDDATE_MUST_BE_FILLED_300X = 3008;  //!FIXME duplicity with 2006
    const DUPLICIT_ORDREFID = 3010;
    const COUNT_OF_ORDERS_IS_GREATER_THAN_MAX_LIMIT = 3011;
    const LIMIT_OF_PACKAGES_PER_ORDER = 3012;
    
    
    // GetNumberRange
    const YOU_HAVE_ALREADY_UNSUSED_NUMBERS_OF_REQUESTED_RANGE_CONTACT_SALES_OR_TECHNICIAN_OR_IT = 4000;
    const PACKPRODUCTTYPE_DOES_NOT_EXIST = 4001;
    const QUANTITY_IS_ABOVE_MAXIMUM = 4002;
    const QUANTITY_IS_BELLOW_MINIMUM = 4003;
    CONST GLOBAL_ERROR_AS36 = 'AS36';
}
